### ISSUE TITLE
problem, when indexing vcf

### ISSUE THREAD

**Issue by aurelBZH** [BSGOxford/BrowseVCF#2]
hello,
Thanks for the work on BrowseVCF. I have tested the software with your sample vcf and other vcf  and can't index any of them in your application. The first step seem to work well but at the second step when after choosing the items i try to click on index selected items i have an error and can't do anything.
![browsevcf_error](https://user-images.githubusercontent.com/9987970/34948868-aa325522-fa0e-11e7-9097-8b2b000f5bd2.png)

**Comment by silvia-s** [comment]
Hi aurelBZH,

Could you please provide some more information regarding the issue you encountered? In particular, it would be useful to know:
- the operating system and web browser you are using
- which version of BrowseVCF reported that error message
- does the error come up also for the sample VCF file available from the software release page, or only with your personal data sets?
- does the BrowseVCF's path contain any spaces?

Thanks!

**Comment by aurelBZH** [comment]
Hi,
Of course i can :)
I'm using Linux Mint 18.2 Sonya and Mozilla Firefox 57.0.4.
I had this error with BrowseVCF 2.8 .
It came with the vcf you're provided and with my dataset . 
BrowseVCF is located at /home/my_usr_name/Téléchargements/BrowseVCF_gnu_2.8 without any space .

thanks for your help

**Comment by silvia-s** [comment]
Thanks for the info. BrowseVCF cannot handle the accents in your path, so the best solution would be to move the BrowseVCF folder (and any VCF input files) from that folder to an ASCII-character-only folder. Alternatively, the command-line version should work seamlessly.
Hope this helps!
Silvia

**Comment by fhashemi125** [comment]
Thank you for developing this platform. I am using Windows 7 (64-bit) and I couldn't upload your sample vcf file. The software just shows loading VCF and finally it don't upload any file. 

![untitled](https://user-images.githubusercontent.com/13817869/37520371-f756b47c-2931-11e8-83c5-efad5ad7e26c.png)

**Comment by silvia-s** [comment]
Could you please try moving the BrowseVCF folder (as well as the input VCF file) to a path that doesn't contain any spaces (e.g. on the Desktop)? I guess that might be the cause of the problem.

**Comment by fhashemi125** [comment]
Thank you! The problem has solved!
