### ISSUE TITLE
error on load vcf

### ISSUE THREAD

**Issue by Abdul194** [BSGOxford/BrowseVCF#4]
I am facing the formating problem when load .vcf file. I have completely run the sample file but when I load my own file it raises a prompt with a formatting error message. actually I have a vcf file that is annotated by the SnpEff annotation tool. when I run my .vcf file without annotation it runs successfully but when it annotated it raise the formatting problem. 
Could you please give me some advice?

Thank you in advance

**format of INFO field without annotation:**
_SGB=-0.379885;MQ0F=0;MQ=60;DP=1;DP4=0,0,1,0;AN=1;AC=1_

**format of Info filed after annotating with SnpEff**
_DP=1;SGB=-0.379885;MQ0F=0;AC=1;AN=1;DP4=0,0,1,0;MQ=60;CSQ=T|upstream_gene_variant|MODIFIER|ORF1ab|GU280_gp01|transcript|GU280_gp01|protein_coding||c.-25C>T|||||25|,T|upstream_gene_variant|MODIFIER|ORF1ab|GU280_gp01|transcript|YP_009725297.1|protein_coding||c.-25C>T|||||25|WARNING_TRANSCRIPT_NO_STOP_CODON,T|upstream_gene_variant|MODIFIER|ORF1ab|GU280_gp01|transcript|YP_009742608.1|protein_coding||c.-25C>T|||||25|WARNING_TRANSCRIPT_NO_STOP_CODON,T|upstream_gene_variant|MODIFIER|ORF1ab|GU280_gp01|transcript|GU280_gp01.2|protein_coding||c.-25C>T|||||25|,T|upstream_gene_variant|MODIFIER|ORF1ab|GU280_gp01|transcript|YP_009725298.1|protein_coding||c.-565C>T|||||565|WARNING_TRANSCRIPT_NO_START_CODON,T|upstream_gene_variant|MODIFIER|ORF1ab|GU280_gp01|transcript|YP_009742609.1|protein_coding||c.-565C>T|||||565|WARNING_TRANSCRIPT_NO_START_CODON,T|upstream_gene_variant|MODIFIER|ORF1ab|GU280_gp01|transcript|YP_009725299.1|protein_coding||c.-2479C>T|||||2479|WARNING_TRANSCRIPT_NO_START_CODON,T|upstream_gene_variant|MODIFIER|ORF1ab|GU280_gp01|transcript|YP_009742610.1|protein_coding||c.-2479C>T|||||2479|WARNING_TRANSCRIPT_NO_START_CODON,T|intergenic_region|MODIFIER|CHR_START-ORF1ab|CHR_START-GU280_gp01|intergenic_region|CHR_START-GU280_gp01|||n.241C>T||||||_

**and header of INFO is**
_##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">_

**Comment by silvia-s** [comment]
Hi Abdul,

Could you please let us know the exact formatting error message you were prompted with?

Given the information you posted, you could try doing the following:

- If you are using a Windows machine, open your VCF file with an editor that preserves line endings and does not introduce special Windows characters (e.g. `\r` or `^M`) for example Notepad++; 

- Change your header line for the INFO field with the following one: 
`##INFO=<ID=ANN,Number=.,Type=String,Description="Format: Allele|Annotation|Annotation_Impact|Gene_Name|Gene_ID|Feature_Type|Feature_ID|Transcript_BioType|Rank|HGVS.c|HGVS.p|cDNA.pos_cDNA.length|CDS.pos_CDS.length|AA.pos_AA.length|Distance|ERRORS_WARNINGS_INFO">`
 ...then save it, re-launch BrowseVCF, and try again processing your modified VCF file. 

Hopefully, this will solve your issue. If not, it might be good if you could send us your VCF file, or at least a subset of it containing the full header section, to test it thoroughly on our side.

Cheers,
Silvia

**Comment by Abdul194** [comment]
yes sure, below is the screen shot of the error that i am getting


![Screenshot (55)](https://user-images.githubusercontent.com/46160584/85853202-8cff3100-b7cb-11ea-8cf6-b891fa821a56.png)
 

**my vcf file is this**
https://drive.google.com/open?id=10xaFzTlxEvpteApLxNEeIZp8vcbc4KZ4&authuser=abdul.rehman%40kics.edu.pk&usp=drive_fs

**Comment by Abdul194** [comment]
Next, I paste the INFO header that you suggest and it loaded the file but on the indexing level, it did not show the attribute of INFO as see in the below image.  Further, I index on available columns but on clicking the "index selected fields" button I show the same error that is posted in the previous comment. 
![Screenshot (57)](https://user-images.githubusercontent.com/46160584/85854322-9f7a6a00-b7cd-11ea-9490-a9ad6144c531.png)

**Comment by silvia-s** [comment]
Hmm, that's weird... Could you please upload your VCF file here, so that I can have a look at it and try to find out what's going on? If it's private data, feel free to use my email address, instead (you can find it at the bottom of the README file for this repository).

**Comment by Abdul194** [comment]
Hye @silvia-s,
the problem is during the copy/paste. I paste your headers by using notepad++ and now it works fine. again thanks to you for your contribution that really helped me.

**Comment by silvia-s** [comment]
That's great! I'm glad that my suggestion was helpful for solving the problem :)

Best,
Silvia

**Comment by Abdul194** [comment]
Hye Silvia, 
last time your suggestion was fine and work properly for my Covid-19 variants (vcf file). Now I generated the variant file for Bat coronavirus and now it raise same formatting error after replacing the header that you suggested.
please give me any other suggestion that generic and work for ma all variants file.  
Thanks in advance

**Comment by Abdul194** [comment]
BAT_Ann_Variants.vcf (file://DESKTOP-AEQNR43/Users/BRL/Downloads/DNA%20Sequences/Combine%20sequences/Annotated%20Variants/BAT_Ann_Variants.vcf)

**Comment by Abdul194** [comment]
sample file
https://www.dropbox.com/t/yCFF0UImcRpzO0Km

**Comment by silvia-s** [comment]
It looks like Wormtable is trying to interpret the genotype likelihoods field as a list of integers, but then throws an error when it finds missing likelihoods (i.e. a dot). A solution to this would be changing the FORMAT header line for PL to the following: 
`##FORMAT=<ID=PL,Number=.,Type=String,Description="List of Phred-scaled genotype likelihoods">`. 

I would also suggest you to modify the INFO header lines for LOF and NMD (similarly to what you already did for the ANN field) to the following:

`##INFO=<ID=LOF,Number=.,Type=String,Description="Predicted loss of function effects for this variant. Format: Gene_Name|Gene_ID|Number_of_transcripts_in_gene|Percent_of_transcripts_affected">`

`##INFO=<ID=NMD,Number=.,Type=String,Description="Predicted nonsense mediated decay effects for this variant. Format: Gene_Name|Gene_ID|Number_of_transcripts_in_gene|Percent_of_transcripts_affected">`

I've tested your (modified) VCF file on my laptop and it worked fine.

Cheers,
Silvia

**Comment by Abdul194** [comment]
Now, this solution is working on my all vcf files. 
Once again thanks @silvia-s,

**Comment by Abdul194** [comment]
Hye @silvia-s 
Once again I am facing a problem of the same type for my new file even pasting all headers that you suggest. Respected Maam can you let me know, what is the problem in the below file. One more thing is that can you tell the agenda behind replacing the headers?  so that, next time I handle the problem myself.
advance thanks again 
link of the file:
https://www.dropbox.com/t/OMV0fxuQuTiBrqGT

**Comment by silvia-s** [comment]
Hi Abdul,

I just downloaded your VCF file and I think it's broken. If you look at the following screenshot (the output of the command `less -S -N COVID_Final_Ann_Variants.vcf`), you'll notice that the content of your file is fine until line 3946 inclusive, but then looks like a binary file from the following line onwards. I would suggest to double-check the commands you used to create this VCF file, amend any errors, and re-check the content of your file before using it into BrowseVCF.

![Screenshot from 2020-07-15 14-38-06](https://user-images.githubusercontent.com/9861211/87547243-bad8e680-c6a2-11ea-96d1-b6c8cf625771.png)

By the way, this software is no longer supported since July 2020 (please see the latest update on the README file) so I cannot offer you much more help beyond this point, I'm afraid :(

All the best,
Silvia

**Comment by kkapuria3** [comment]
> 
> 
> Hye @silvia-s
> Once again I am facing a problem of the same type for my new file even pasting all headers that you suggest. Respected Maam can you let me know, what is the problem in the below file. One more thing is that can you tell the agenda behind replacing the headers? so that, next time I handle the problem myself.
> advance thanks again
> link of the file:
> https://www.dropbox.com/t/OMV0fxuQuTiBrqGT

Yes, if you could just briefly let us know how changing headers affects and fixes vcf parsing problem.

**Comment by silvia-s** [comment]
Hi Karan,

The problems I found in Abdul's VCF file were the following:
**1)** the "ANN" (annotation) INFO header line contained white spaces and forward slashes between the pipe-separated fields, as well as unexpected Windows characters (_see 2nd post in this thread_);
**2)** the "PL" (phred-scaled genotype likelihoods) INFO header line contained missing values (indicated by a dot) which Wormtable, the Python module behind BrowseVCF, cannot handle (_see 10th post in this thread_).

In general, problems like **1)** can be avoided by: (A) using an editor like Notepad++ that preserves line endings without introducing special Windows characters, and (B) removing any special characters other than "_" within the "Description" part of each header line. Problems like **2)** can be bypassed by changing the "Number" and "Type" specification of the header line; for example, I suggested Abdul to replace "Number=G,Type=Integer" with "Number=.,Type=String" and this helped him to solve the VCF parsing problem. 

I don't recall any other issue related to the header formatting, but if you find and solve a new one, please post your solution here so it can be of help to other users.

Cheers,
Silvia
